version: '3.9'
services:
  app:
    build:
      context: .
    container_name: cache-app
    ports:
      - "3000:3000" # Mapea el puerto local al puerto del contenedor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:7"
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # Configuración persistente
